#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# @description      Microwebserver for serving all these local files on the web
#
# @author           Andrea Benini
# @date             2023-11-07
# @license          GNU Affero General Public License v3.0
# @see              Used from local browser or from a smartphone to provide
#                   controller software for dealing with robots
#
# pyright: reportMissingImports=false
#
import http.server
import socketserver
PORT = 8000

Handler = http.server.SimpleHTTPRequestHandler
with socketserver.TCPServer(("", PORT), Handler) as httpd:
    print("Serving at port", PORT)
    httpd.serve_forever()
